#define IMGUI_IMPL_OPENGL_LOADER_GLAD
//#define IMGUI_DISABLE_STB_TRUETYPE_IMPLEMENTATION
//#define STB_TRUETYPE_IMPLEMENTATION
#include <imgui.cpp>
//#include <imgui_demo.cpp>
#include <imgui_draw.cpp>
#include <imgui_tables.cpp>
#include <imgui_widgets.cpp>
#include <imgui_impl_opengl3.cpp>
#include <imgui_impl_glfw.cpp> 